#!/bin/sh
git fetch --all

git checkout -B __FFETCH_AUX

git reset --hard upstream/qa
git tfs fetch -i qa

git reset --hard upstream/integration
git tfs fetch -i integration

git reset --hard upstream/develop
git tfs fetch -i default

git checkout -
git branch -D __FFETCH_AUX

